# Generated by Django 4.2.4 on 2023-08-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_city_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
