# Generated by Django 4.2.4 on 2023-08-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_enduser_remove_city_country_city_creation_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndUser',
            new_name='APIUser',
        ),
    ]
